"""
Modules 5, 7, 9 - Keyword Intelligence, SERP Intelligence, Rank Tracking.

Keyword is the tracked term itself. SERPSnapshot is one point-in-time
capture of search results for that keyword (kept as history, never
overwritten - Module 8/42 need to diff snapshots over time to detect
intent shifts and algorithm volatility). RankRecord is the position
extracted from a snapshot for OUR site specifically, denormalized out
for fast trend queries without re-parsing every snapshot's JSON.
"""
import uuid

from sqlalchemy import JSON, Boolean, Float, ForeignKey, Integer, String
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base
from app.models.mixins import FullAuditableMixin


class Keyword(Base, FullAuditableMixin):
    __tablename__ = "keywords"

    business_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("businesses.id"))
    term: Mapped[str] = mapped_column(String(512))
    language: Mapped[str] = mapped_column(String(8), default="en")
    location: Mapped[str | None] = mapped_column(String(128), nullable=True)  # e.g. "Delhi, India"
    intent: Mapped[str | None] = mapped_column(String(32), nullable=True)     # informational/commercial/transactional/navigational/local
    funnel_stage: Mapped[str | None] = mapped_column(String(32), nullable=True)  # awareness/consideration/decision
    search_volume: Mapped[int | None] = mapped_column(Integer, nullable=True)
    is_seed: Mapped[bool] = mapped_column(Boolean, default=True)   # seed keyword vs. generated by fan-out
    parent_keyword_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("keywords.id"), nullable=True
    )  # set when this keyword came from fan-out of another

    snapshots: Mapped[list["SERPSnapshot"]] = relationship(back_populates="keyword", cascade="all, delete-orphan")
    rank_records: Mapped[list["RankRecord"]] = relationship(back_populates="keyword", cascade="all, delete-orphan")


class SERPSnapshot(Base, FullAuditableMixin):
    __tablename__ = "serp_snapshots"

    keyword_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("keywords.id"))
    device: Mapped[str] = mapped_column(String(16), default="desktop")  # desktop | mobile
    provider: Mapped[str] = mapped_column(String(32))  # "dataforseo" | "own"

    organic_results: Mapped[list | None] = mapped_column(JSON, nullable=True)  # [{position, url, title, snippet, domain}]
    local_pack: Mapped[list | None] = mapped_column(JSON, nullable=True)
    featured_snippet: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    people_also_ask: Mapped[list | None] = mapped_column(JSON, nullable=True)
    ai_overview: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    raw_response: Mapped[dict | None] = mapped_column(JSON, nullable=True)  # full provider payload, for debugging/reprocessing

    keyword: Mapped["Keyword"] = relationship(back_populates="snapshots")


class RankRecord(Base, FullAuditableMixin):
    """Denormalized: our site's own position, extracted from a SERPSnapshot,
    for fast 'show me the rank trend for this keyword' queries."""
    __tablename__ = "rank_records"

    keyword_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("keywords.id"))
    snapshot_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("serp_snapshots.id"))
    url: Mapped[str | None] = mapped_column(String(1024), nullable=True)  # which of our URLs ranked, if any
    position: Mapped[int | None] = mapped_column(Integer, nullable=True)  # null = not found in top results captured
    device: Mapped[str] = mapped_column(String(16), default="desktop")

    keyword: Mapped["Keyword"] = relationship(back_populates="rank_records")
