"""Phase 3: keywords, SERP snapshots, rank records

Revision ID: 0de2d7eb2d08
Revises: f6addb60bad0
Create Date: 2026-09-14 10:53:13.776682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0de2d7eb2d08'
down_revision: Union[str, None] = 'f6addb60bad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keywords',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('term', sa.String(length=512), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('intent', sa.String(length=32), nullable=True),
    sa.Column('funnel_stage', sa.String(length=32), nullable=True),
    sa.Column('search_volume', sa.Integer(), nullable=True),
    sa.Column('is_seed', sa.Boolean(), nullable=False),
    sa.Column('parent_keyword_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['parent_keyword_id'], ['keywords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('serp_snapshots',
    sa.Column('keyword_id', sa.UUID(), nullable=False),
    sa.Column('device', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('organic_results', sa.JSON(), nullable=True),
    sa.Column('local_pack', sa.JSON(), nullable=True),
    sa.Column('featured_snippet', sa.JSON(), nullable=True),
    sa.Column('people_also_ask', sa.JSON(), nullable=True),
    sa.Column('ai_overview', sa.JSON(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rank_records',
    sa.Column('keyword_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('device', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['serp_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rank_records')
    op.drop_table('serp_snapshots')
    op.drop_table('keywords')
    # ### end Alembic commands ###
