"""Phase 4: page quality, schema recs, content gaps, decay alerts

Revision ID: 6372486872c4
Revises: 0de2d7eb2d08
Create Date: 2026-09-15 20:14:57.931573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6372486872c4'
down_revision: Union[str, None] = '0de2d7eb2d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_decay_alerts',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('previous_crawl_job_id', sa.UUID(), nullable=False),
    sa.Column('current_crawl_job_id', sa.UUID(), nullable=False),
    sa.Column('decay_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['current_crawl_job_id'], ['crawl_jobs.id'], ),
    sa.ForeignKeyConstraint(['previous_crawl_job_id'], ['crawl_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_gaps',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('keyword_id', sa.UUID(), nullable=False),
    sa.Column('keyword_term', sa.String(length=512), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('matched_url', sa.String(length=1024), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page_quality_scores',
    sa.Column('crawled_page_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('component_scores', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['crawled_page_id'], ['crawled_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schema_recommendations',
    sa.Column('crawled_page_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('recommended_type', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('suggested_jsonld', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['crawled_page_id'], ['crawled_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schema_recommendations')
    op.drop_table('page_quality_scores')
    op.drop_table('content_gaps')
    op.drop_table('content_decay_alerts')
    # ### end Alembic commands ###
