"""Phase 2: crawl jobs, crawled pages, technical issues

Revision ID: f6addb60bad0
Revises: 81bd0be2109d
Create Date: 2026-09-14 04:05:24.569633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6addb60bad0'
down_revision: Union[str, None] = '81bd0be2109d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_jobs',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('start_url', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('max_pages', sa.Integer(), nullable=False),
    sa.Column('max_depth', sa.Integer(), nullable=False),
    sa.Column('pages_crawled', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crawled_pages',
    sa.Column('crawl_job_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('h1', sa.JSON(), nullable=True),
    sa.Column('h2', sa.JSON(), nullable=True),
    sa.Column('h3', sa.JSON(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('canonical_url', sa.String(length=1024), nullable=True),
    sa.Column('robots_meta', sa.String(length=128), nullable=True),
    sa.Column('is_noindex', sa.Boolean(), nullable=False),
    sa.Column('viewport', sa.String(length=255), nullable=True),
    sa.Column('internal_links', sa.JSON(), nullable=True),
    sa.Column('external_links', sa.JSON(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('open_graph', sa.JSON(), nullable=True),
    sa.Column('redirect_chain', sa.JSON(), nullable=True),
    sa.Column('discovered_via', sa.String(length=32), nullable=True),
    sa.Column('crawl_depth', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['crawl_job_id'], ['crawl_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technical_issues',
    sa.Column('crawl_job_id', sa.UUID(), nullable=False),
    sa.Column('issue_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('affected_url', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('recommended_fix', sa.Text(), nullable=True),
    sa.Column('auto_fix_eligible', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['crawl_job_id'], ['crawl_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('technical_issues')
    op.drop_table('crawled_pages')
    op.drop_table('crawl_jobs')
    # ### end Alembic commands ###
